version: "3.7"

services:

  nextcloud:
    image: tiredofit/nextcloud:29-latest
    container_name: nextcloud
    volumes:
      - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
      - ./data/data:/data/userdata
      - ./data/config:/www/nextcloud/config
      - ./data/apps:/data/apps
      - ./data/themes:/www/nextcloud/themes
      - ./logs:/www/logs
      - ./data/templates:/data/templates
    environment:
      - CRON_PERIOD=5
      - ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - ADMIN_PASS=${NEXTCLOUD_ADMIN_PASSWORD}
      - DOMAIN=${APP_DOMAIN}
      - ENABLE_FAIL2BAN=FALSE
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASS=password
      - DB_HOST=nextcloud-db
      - POSTGRES_HOST=db-nextcloud
      - REDIS_HOST=redis-nextcloud
      - POSTGRES_PASSWORD=tipi
      - POSTGRES_USER=tipi
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - TRUSTED_PROXIES=172.16.0.0/12
      - OVERWRITEPROTOCOL=${APP_PROTOCOL:-http}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.nextcloud.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.routers.nextcloud.tls.certresolver: myresolver
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.http.middlewares.nextcloud.headers.browserXSSFilter: true
      traefik.http.middlewares.nextcloud.headers.contentTypeNosniff: true
      traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.nextcloud.headers.stsPreload: true
      traefik.http.middlewares.nextcloud.headers.stsSeconds: 155520011
      traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent: true
      traefik.http.middlewares.nextcloud_redirect.redirectregex.regex: https://(.*)/.well-known/(card|cal)dav
      traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement: https://$${1}/remote.php/dav/
      traefik.http.routers.nextcloud.middlewares: nextcloud,nextcloud_redirect,nextcloud-https
      traefik.http.middlewares.nextcloud.headers.customRequestHeaders.X-Forwarded-Proto: https
      traefik.http.middlewares.nextcloud-https.redirectscheme.scheme: https
      traefik.http.routers.nextcloud-http.middlewares: nextcloud-https@docker
    #labels:
      #- traefik.enable=true
      #- traefik.http.routers.nextcloud.rule=Host(`nextcloud.example.com`)
      #- traefik.http.services.nextcloud.loadbalancer.server.port=80
      #- traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      #- traefik.http.middlewares.nextcloud-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      #- traefik.http.middlewares.nextcloud-rep.redirectregex.replacement=https://$$1/remote.php/dav/
      #- traefik.http.middlewares.nextcloud-rep.redirectregex.permanent=true
      #- traefik.http.middlewares.nextcloud-header.headers.stsIncludeSubdomains=true
      #- traefik.http.middlewares.nextcloud-header.headers.stsSeconds=15552000
      #- traefik.http.routers.nextcloud-app.middlewares=nextcloud-rep,nextcloud-header
