version: "3.7"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/app/data
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:3001
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.uptime-kuma-web-redirect.redirectscheme.scheme: https
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
      # Web
      traefik.http.routers.uptime-kuma-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.uptime-kuma-insecure.entrypoints: web
      traefik.http.routers.uptime-kuma-insecure.service: uptime-kuma
      traefik.http.routers.uptime-kuma-insecure.middlewares: uptime-kuma-web-redirect
      # Websecure
      traefik.http.routers.uptime-kuma.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.uptime-kuma.entrypoints: websecure
      traefik.http.routers.uptime-kuma.service: uptime-kuma
      traefik.http.routers.uptime-kuma.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.uptime-kuma-local-insecure.rule: Host(`uptime-kuma.${LOCAL_DOMAIN}`)
      traefik.http.routers.uptime-kuma-local-insecure.entrypoints: web
      traefik.http.routers.uptime-kuma-local-insecure.service: uptime-kuma
      traefik.http.routers.uptime-kuma-local-insecure.middlewares: uptime-kuma-web-redirect
      # Local domain secure
      traefik.http.routers.uptime-kuma-local.rule: Host(`uptime-kuma.${LOCAL_DOMAIN}`)
      traefik.http.routers.uptime-kuma-local.entrypoints: websecure
      traefik.http.routers.uptime-kuma-local.service: uptime-kuma
      traefik.http.routers.uptime-kuma-local.tls: true
      
 # autokuma:
    #image: ghcr.io/bigboot/autokuma:latest
   # restart: unless-stopped
   # environment:
    #  AUTOKUMA__KUMA__URL: http://localhost:3001
      # AUTOKUMA__KUMA__USERNAME: <username> 
      # AUTOKUMA__KUMA__PASSWORD: <password>
      # AUTOKUMA__KUMA__MFA_TOKEN: <token>
      # AUTOKUMA__KUMA__HEADERS: "<header1_key>=<header1_value>,<header2_key>=<header2_value>,..."
      # AUTOKUMA__KUMA__CALL_TIMEOUT: 5s
      # AUTOKUMA__KUMA__CONNECT_TIMEOUT: 5s
      # AUTOKUMA__TAG_NAME: AutoKuma
      # AUTOKUMA__TAG_COLOR: "#42C0FB"
      # AUTOKUMA__DEFAULT_SETTINGS: |- 
      #    docker.docker_container: {{container_name}}
      #    http.max_redirects: 10
      #    *.max_retries: 3
      # AUTOKUMA__DOCKER__SOCKET: /var/run/docker.sock
      # AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
      
  #  volumes:
   #   - /var/run/docker.sock:/var/run/docker.sock
